const Data = [
  {
    id: 1,
    posted_by: 1,
    suite_number: 68739,
    street: "526 Caliangt Way",
    neighborhood: "Bent Avens",
    city: "Van Nuys",
    state: "CA",
    zipcode: "91411",
    bedrooms: 3,
    bathrooms: 1,
    rent: 78,
    utilities: 26,
    pref_gender: "Female",
    is_private_room: "yes",
    move_in_date: "1/27/2024",
    move_out_date: "9/26/2024",
  },
  {
    id: 2,
    posted_by: 2,
    suite_number: 62979,
    street: "2 Corben Point",
    neighborhood: "Narrow Helmet Orchid",
    city: "Montgomery",
    state: "AL",
    zipcode: "36134",
    bedrooms: 2,
    bathrooms: 5,
    rent: 413,
    utilities: 164,
    pref_gender: "Male",
    is_private_room: "yes",
    move_in_date: "8/30/2024",
    move_out_date: "9/5/2024",
  },
  {
    id: 3,
    posted_by: 3,
    suite_number: 98566,
    street: "8 Kim Lane",
    neighborhood: "Nootka Lupine",
    city: "Daytona Beach",
    state: "FL",
    zipcode: "32118",
    bedrooms: 3,
    bathrooms: 3,
    rent: 1863,
    utilities: 121,
    pref_gender: "Female",
    is_private_room: "no",
    move_in_date: "4/12/2024",
    move_out_date: "1/27/2024",
  },
  {
    id: 4,
    posted_by: 4,
    suite_number: 50631,
    street: "6423 Old Gate Drive",
    neighborhood: "Buttecandle",
    city: "Norfolk",
    state: "VA",
    zipcode: "23551",
    bedrooms: 3,
    bathrooms: 2,
    rent: 529,
    utilities: 409,
    pref_gender: "Male",
    is_private_room: "no",
    move_in_date: "1/19/2024",
    move_out_date: "5/9/2024",
  },
  {
    id: 5,
    posted_by: 4,
    suite_number: 41053,
    street: "582 Forest Dale Parkway",
    neighborhood: "Atlantic Cup Lichen",
    city: "Grand Rapids",
    state: "MI",
    zipcode: "49505",
    bedrooms: 1,
    bathrooms: 4,
    rent: 1407,
    utilities: 131,
    pref_gender: "Female",
    is_private_room: "no",
    move_in_date: "12/15/2024",
    move_out_date: "1/29/2024",
  },
  {
    id: 6,
    posted_by: 1,
    suite_number: 40522,
    street: "02 Mariners Cove Street",
    neighborhood: "Peidmont Quillwort",
    city: "Dallas",
    state: "TX",
    zipcode: "75231",
    bedrooms: 1,
    bathrooms: 2,
    rent: 1555,
    utilities: 140,
    pref_gender: "Male",
    is_private_room: "no",
    move_in_date: "1/1/2024",
    move_out_date: "4/19/2024",
  },
  {
    id: 7,
    posted_by: 3,
    suite_number: 31083,
    street: "5965 Lighthouse Bay Plaza",
    neighborhood: "Arizona Ragwort",
    city: "Salt Lake City",
    state: "UT",
    zipcode: "84135",
    bedrooms: 5,
    bathrooms: 3,
    rent: 796,
    utilities: 212,
    pref_gender: "Male",
    is_private_room: "no",
    move_in_date: "6/11/2024",
    move_out_date: "3/31/2024",
  },
  {
    id: 8,
    posted_by: 3,
    suite_number: 78750,
    street: "54435 Pennsylvania Terrace",
    neighborhood: "Longleaf False Goldeneye",
    city: "Dallas",
    state: "TX",
    zipcode: "75367",
    bedrooms: 4,
    bathrooms: 5,
    rent: 1409,
    utilities: 338,
    pref_gender: "Male",
    is_private_room: "no",
    move_in_date: "8/23/2024",
    move_out_date: "6/4/2024",
  },
  {
    id: 9,
    posted_by: 2,
    suite_number: 7723,
    street: "1 Russell Trail",
    neighborhood: "Prairie Sunflower",
    city: "Winston Salem",
    state: "NC",
    zipcode: "27150",
    bedrooms: 1,
    bathrooms: 4,
    rent: 342,
    utilities: 307,
    pref_gender: "Male",
    is_private_room: "yes",
    move_in_date: "7/14/2024",
    move_out_date: "1/11/2024",
  },
  {
    id: 10,
    posted_by: 4,
    suite_number: 79447,
    street: "09562 Calypso Road",
    neighborhood: "Carolina Fluffgrass",
    city: "Burbank",
    state: "CA",
    zipcode: "91520",
    bedrooms: 4,
    bathrooms: 5,
    rent: 1702,
    utilities: 196,
    pref_gender: "Female",
    is_private_room: "yes",
    move_in_date: "11/24/2024",
    move_out_date: "7/8/2024",
  },
];

export default Data;